config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  resources :events do
    resources :participants

    member do
      get :generator
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :participants
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_user, only: [:index, :new, :create]
  before_action :set_event, only: [:show, :edit, :update, :generator]

  def index
    @events = Event.where(user: @user)
  end

  def new
    @event = @user.events.build
  end

  def show
    @participant = Participant.new
  end

  def create
    @event = @user.events.build(event_params)
    if @event.save!
      event_creator_is_participant(@user, @event)
      flash[:notice] = "L'évènement à bien été créé !"
      redirect_to event_path(@event)
    else
      flash[:alert] = "L'évènement n'a pas pu être créé !"
      render :new
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      flash[:notice] = "Vos modifications ont bien été prisent en compte !"
      redirect_to event_path(@event)
    else
      flash[:alert] = "Vos modifications n'ont pas bien été prisent en compte !"
      render :edit
    end
  end

  def generator
    participants = @event.participants
    MakeAssociations.new(participants, @event).generationAssociation

    flash[:notice] = "Un email a été envoyé à chaques utilisateurs !"
    redirect_to event_path(@event)
  end

  private

  def set_user
    @user = current_user
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :price)
  end

  def event_creator_is_participant(user, event)
    Participant.create(user_name: user.user_name, email: user.email, event: event)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<div class="form-wrapper">
  <div class="form">
    <h2>Modifier l'évévenement</h2>

    <%= form_for(@event) do |f| %>

      <div class="field">
        <%= f.text_field :title, placeholder: "Titre de l'événement", class: "form-field" %>
      </div>

      <div class="field">
        <%= f.number_field :price, placeholder: "Prix du cadeau", class: "form-field" %>
      </div>

      <div class="actions">
        <%= f.submit "Modifier", id: 'button-valid' %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<div class="events-index-wrapper">
  <div class="events-index">
    <% if @events.empty? %>
      <h1>Vous n'avez pas encore d'événements !</h1>
    <% else %>
      <h1>Mes événements:</h1>
    <% end %>

    <% @events.each do |event| %>
      <%= render 'shared/event-card', event: event %>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<div class="form-wrapper">
  <div class="form">
    <h2>Créer un événement</h2>

    <%= form_for(@event) do |f| %>

      <div class="field">
        <%= f.text_field :title, placeholder: "Titre de l'événement", class: "form-field" %>
      </div>

      <div class="field">
        <%= f.number_field :price, placeholder: "Prix du cadeau", class: "form-field" %>
      </div>

      <div class="actions">
        <%= f.submit "Créer l'événement", id: 'button-valid' %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<div class="event-show-wraper">
  <div class="event-show">
    <div class="event-info-wrapper">
      <div class="event-info">
        <h2>Evénement: <%= @event.title %> </h2>
        <h2>Prix du cadeau: <%= @event.price %> euros</h2>
      </div>

      <%= link_to "Modifier l'évévenement", edit_event_path(@event), id: 'button-classic' %>
    </div>


    <div class="participants-wrapper">
      <h3>Participants: </h3>
      <% @event.participants.each do |participant| %>
        <%= render 'shared/participant-card', participant: participant, event: @event %>
      <% end %>
    </div>

    <div class="add-participants-form-wrapper">
      <h3>Ajouter des participants:</h3>

      <%= form_for [@event, @participant] do |f| %>

        <div class="add-participants-form">
          <div class="field">
            <%= f.text_field :user_name, placeholder: 'Prénom', class: 'form-field' %>
          </div>

          <div class="field">
            <%= f.email_field :email, placeholder: 'Adresse mail', class: 'form-field' %>
          </div>

          <div class="actions">
            <%= f.submit "Ajouter", id: 'button-add' %>
          </div>
        <% end %>
        </div>
    </div>


    <div class="generate-link">
       <%= link_to 'Générer', generator_event_path(@event), id: 'button-create'  %>
    </div>

  </div>
</div>