config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  resources :events do
    resources :participants

    member do
      get :generator
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecretSantaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <div class="nav-bar">
      <div class="nav-bar-left">
        <%= link_to 'Home', root_path  %>
        <% if user_signed_in? %>
          <%= link_to 'Mes événements', events_path %>
        <% end %>
      </div>
      <div class="nav-bar-right">
      <% if user_signed_in? %>
        <%= link_to 'Se déconnecter', destroy_user_session_path, method: :delete %>
        <p> <%= current_user.user_name %> </p>
      <% else %>
        <%= link_to 'Se connecter', user_session_path  %>
        <%= link_to "S'enregistrer", new_user_registration_path %>
      <% end %>
      </div>
    </div>

    <div class="layout">
      <% flash.each do |key, message| %>
        <div class="alert alert-<%= key %>">
            <%= message %>
        </div>
      <% end %>

      <%= yield %>

    </div>

  </body>
</html>